# Generated by Django 5.1.2 on 2024-10-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_post_friend_share'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='share',
            name='sharer',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
