# Generated by Django 5.1.2 on 2024-10-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
