# Generated by Django 5.1.2 on 2024-10-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_delete_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
