# Generated by Django 5.1.2 on 2024-10-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_alter_author_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
