# Generated by Django 5.1.2 on 2024-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_remotenode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotenode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='password',
        ),
        migrations.AddField(
            model_name='remotenode',
            name='auth_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='remotenode',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
