# Generated by Django 5.1.2 on 2024-11-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_remove_remotenode_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotenode',
            old_name='auth_token',
            new_name='token',
        ),
    ]
