# Generated by Django 5.1.2 on 2024-11-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_nodesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_user_signup', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NodeSettings',
        ),
    ]
