# Generated by Django 5.1.2 on 2024-11-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0013_sitesettings_delete_nodesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
