# Generated by Django 5.1.2 on 2024-11-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
    ]
