# Generated by Django 5.1.2 on 2024-11-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_alter_sitesettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_user_approval', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
