# Generated by Django 5.1.2 on 2024-11-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0018_alter_author_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
