# Generated by Django 5.1.2 on 2024-11-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0020_alter_author_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotenode',
            name='token',
        ),
        migrations.AddField(
            model_name='remotenode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='remotenode',
            name='password',
            field=models.CharField(default='password', max_length=250),
        ),
    ]
