# Generated by Django 5.1.2 on 2024-11-24 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0020_alter_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='remote_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.remotenode'),
        ),
    ]
