# Generated by Django 5.1.2 on 2024-11-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0021_author_remote_node'),
        ('authors', '0021_remove_remotenode_token_remotenode_is_active_and_more'),
    ]

    operations = [
    ]
