# Generated by Django 5.1.2 on 2024-11-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0021_remove_remotenode_token_remotenode_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
