# Generated by Django 5.1.2 on 2024-11-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0021_inbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
