# Generated by Django 5.1.2 on 2024-11-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0021_remove_remotenode_token_remotenode_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='toconnectedto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(default='password', max_length=250)),
            ],
        ),
    ]
