# Generated by Django 5.1.2 on 2024-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0023_toconnectedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='type',
            field=models.CharField(default='incoming', max_length=100),
        ),
    ]
