# Generated by Django 5.1.2 on 2024-11-25 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0023_alter_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='remote_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.remotenode'),
        ),
    ]
