# Generated by Django 5.1.2 on 2024-11-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0024_remotenode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotenode',
            name='url',
            field=models.URLField(),
        ),
    ]
