# Generated by Django 5.1.2 on 2024-11-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0025_alter_remotenode_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotenode',
            name='type',
        ),
    ]
