# Generated by Django 5.1.2 on 2024-11-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0026_remove_remotenode_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='toconnectedto',
            new_name='toconnectIncoming',
        ),
    ]
