# Generated by Django 5.1.2 on 2024-11-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0027_rename_toconnectedto_toconnectincoming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toconnectIncoming',
        ),
        migrations.AlterField(
            model_name='remotenode',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
