# Generated by Django 5.1.2 on 2024-10-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fqid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
