# Generated by Django 5.1.2 on 2024-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_created_at_post_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image'), ('application/base64', 'Other Base64 Image')], default='text/plain', max_length=20),
        ),
    ]
