# Generated by Django 5.1.2 on 2024-10-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image')], default='text/plain', max_length=20),
        ),
    ]
