# Generated by Django 5.1.2 on 2024-11-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.CharField(default='page', max_length=300),
            preserve_default=False,
        ),
    ]
