# Generated by Django 5.1.2 on 2024-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='fqid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
