# Generated by Django 5.1.2 on 2024-11-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_like_fqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Friends Only'), ('DELETED', 'Deleted Post')], default='PUBLIC', max_length=10),
        ),
    ]
